### ISSUE TITLE
WISH: This looks compatible with Firefox already! Please consider submitting to addons.mozilla.org

### ISSUE THREAD

**Issue by cdemwell** [aweary/twitter-required-alt-text#10]
After looking over your code, I noticed that it was likely compatible with Firefox as well - I cloned your repo and tested it, and found that it loaded fine as a temporary extension. It would be quite easy to package and upload for Firefox users to install easily ([here is the Mozilla documentation about packaging](https://extensionworkshop.com/documentation/publish/package-your-extension/)) ([link to Mozilla documentation about submission](https://extensionworkshop.com/documentation/publish/source-code-submission/))

In the interests of a more accessible web, I would be happy to do legwork for this, but I want to respect your wishes. Please consider - this extension can serve more than just Chrome users!

![An image of the Firefox Debugging extension entry for Twitter Required Alt Text, showing that it was added as a temporary extension.](https://user-images.githubusercontent.com/5788774/97790223-06e16580-1b84-11eb-84d9-b9a1aeeda875.png)

![A screenshot of the Twitter reply modal, showing that the extension is requiring me to add alt text before posting by changing the submit button to a red button that says "Add Alt Text"](https://user-images.githubusercontent.com/5788774/97790240-2bd5d880-1b84-11eb-85c8-f6da99492977.png)

![A screenshot showing that, now that alt text has been added to the previous two screenshots, the final submit button is now a blue button that says "Reply"](https://user-images.githubusercontent.com/5788774/97790247-3bedb800-1b84-11eb-8e06-cd4be3e7188e.png)

**Comment by wmww** [comment]
Has any progress on this been made? I have an FF addon in the store already and would also be happy to do this. Is it waiting on someone to take the initiative or is there a reason not to do this?

**Comment by aweary** [comment]
feel free to do this if you have the time!

**Comment by wmww** [comment]
Submitted to addons.mozilla.org. We'll see how long they take to review it.

**Comment by wmww** [comment]
We're live! Issue can be closed. https://addons.mozilla.org/en-US/firefox/addon/twitter-required-alt-text
