### ISSUE TITLE
Tweeting is not blocked on quote tweets with an image

### ISSUE THREAD

**Issue by bnb** [aweary/twitter-required-alt-text#2]
If you quote tweet and add an image, the extension does not force you to add alt-text. 

![image](https://user-images.githubusercontent.com/502396/88304849-c9448500-ccd6-11ea-850b-cddb3ac8f394.png)

**Comment by aweary** [comment]
Interesting, I can't reproduce that! Are you getting any errors in the console?

![image](https://user-images.githubusercontent.com/6886061/88305518-3c49fd80-cccf-11ea-8490-4209933c0a50.png)

**Comment by bnb** [comment]
Hmm. It's working now in a new, non-PWA tab. Looking at the console of the PWA-ified version where it wasn't working, I don't see anything I wouldn't expect 😬

**Comment by aweary** [comment]
Did you perhaps have an in-progress Tweet composed in the main composition interface? I think if there are two active compositions it can end up disabling the one outside the modal, making it look like it's not doing anything.

**Comment by aweary** [comment]
Tracking that issue here: https://github.com/aweary/twitter-required-alt-text/issues/3

**Comment by bnb** [comment]
AFAIK no since I directly opened up the PWA to tweet what I was going to tweet.

**Comment by aweary** [comment]
@bnb does this consistently not work in the PWA version? I didn't test it in the PWA version, I'll have to look into that.

**Comment by bnb** [comment]
afaik seems to be #3. I don't think PWA affects the extension in a way that would change its ability to work.
