### ISSUE TITLE
Does not block tweeting for GIFs without alt descriptions

### ISSUE THREAD

**Issue by bnb** [aweary/twitter-required-alt-text#4]
Seems that GIFs are not blocked from being tweeted without an alt. 

![image](https://user-images.githubusercontent.com/502396/88306991-686a7c00-ccd9-11ea-80ba-91951a65b80b.png)

**Comment by aweary** [comment]
For some reason I thought you couldn't add alt text to GIFs, I must have missed that! I intentionally excluded them, so this actually simplifies things.

**Comment by bnb** [comment]
for quite a while you couldn't, but they added the feature a while back :)

**Comment by aweary** [comment]
Should be fixed by https://github.com/aweary/twitter-required-alt-text/pull/5
