### ISSUE TITLE
WISH: Please license your code

### ISSUE THREAD

**Issue by cdemwell** [aweary/twitter-required-alt-text#9]
I'd like to make a similar extension for Firefox, and I think the best way to do so would be to explicitly add it as a derivative of your code - but without a license, I can't legally do so. Here is Github's explanation of how to do this - it's quite straightforward and I would be happy to provide you with a PR adding an OSS license of your choice.

**Comment by aweary** [comment]
@cdemwell it's now licenses under MIT, thanks!
